# Holdings by licence
# The licence is an SPDX IRI in the graph; the short id in the result is
# derived here the same way the catalogue page derives its facet, so the two
# numbers can be compared. If they ever disagree, one of them is wrong.

PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX crmdig: <http://www.ics.forth.gr/isl/CRMdig/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX fdo: <https://w3id.org/fdo-squirrel/>
PREFIX fdoreg: <https://w3id.org/fdo-squirrel/registry/>
PREFIX geosparql: <http://www.opengis.net/ont/geosparql#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX role: <https://w3id.org/fdo-squirrel/registry/role/>
PREFIX schema: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?licence (COUNT(DISTINCT ?fdo) AS ?fdos)
WHERE {
  ?catalogue a dcat:Catalog ;
             dcat:dataset ?fdo .
  ?fdo dct:license ?url .
  BIND(REPLACE(REPLACE(STR(?url), "^https://spdx.org/licenses/", ""),
               "[.]html$", "") AS ?licence)
}
GROUP BY ?licence
ORDER BY DESC(?fdos) ?licence
